---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Installing Linux Apps
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        install_recommends: yes
        state: present
      loop:
        - vim
        - htop
        - curl
        - wget
        - ncdu
        - tree
        - apt-transport-https
        - ca-certificates
        - gnupg
        - python3-pip
        - make
        - git
        - bash-completion
        - gnupg-agent
        - zsh
        - flameshot
        - fonts-hack
        - tilix
        - virtualbox
        - mlocate
        - krita
        - jq
        - mtr
        - dconf-cli
        - fonts-firacode
        - python-is-python3
        - python3-venv
        - terminator
        - jupyter-server
        - ipython3
        - neofetch
        - vpnc
        - network-manager-vpnc
        - network-manager-vpnc-gnome
        - aptitude
        - gir1.2-gtop-2.0
        - gir1.2-nm-1.0
        - gir1.2-clutter-1.0
        - gnome-system-monitor
        - sshuttle
        - openssh-client
        - python3-openstackclient
        - python3-octaviaclient
        - sshpass
        - vlc
        - libqt5webkit5
        - exa
        - btop
        - flatpak
        - gnome-shell-extension-prefs
        - chrome-gnome-shell
        - gnome-shell-extensions
        - python3-passlib
        - node-typescript
        - python3-pynetbox
        - gnome-weather
        - gnome-calendar
    - name: Install Docker
      block:
        - name: Install Docker Key
          become: true
          apt_key:
            url: "https://download.docker.com/linux/ubuntu/gpg"
            state: present
        - name: Install Docker Repository
          become: true
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            filename: docker-ce
        - name: Install Docker
          become: true
          apt:
            name: docker-ce

        - name: Adding existing user to group Docker
          become: yes
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes

        - name: Install Docker-Compose
          become: true
          get_url:
            url: "https://github.com/docker/compose/releases/download/v2.15.0/docker-compose-linux-x86_64"
            dest: "/usr/local/bin/docker-compose"
            mode: 1755

        - name: Install Docker Machine Bash Completion
          become: true
          get_url:
            url: "https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash"
            dest: "/etc/bash_completion.d/docker-machine"

        - name: Install Docker-Compose Bash Completion
          become: true
          get_url:
            url: "https://raw.githubusercontent.com/docker/compose/1.26.2/contrib/completion/bash/docker-compose"
            dest: "/etc/bash_completion.d/docker-compose"
    - name: Remove libreoffice
      block:
        - name: remove libreoffice
          become: true
          ansible.builtin.shell:
            cmd: 'sudo apt-get remove --purge libreoffice\* -y && sudo apt-get clean -y && sudo apt-get autoremove -y'

        - name: Create a directory if it does not exist vlc
          ansible.builtin.file:
            path: ~/.var/app/org.videolan.VLC/data/vlc/lua
            state: directory
            mode: "0755"

        - name: Ansible copy directory vlc
          ansible.builtin.copy:
            src: files/tunein/
            dest: ~/.var/app/org.videolan.VLC/data/vlc/lua

        - name: Ansible copy directory vlc
          ansible.builtin.copy:
            src: files/tunein/
            dest: ~/.local/share/vlc/lua
    - name: Install zsh
      block:
        - name: Installing Oh-My-zsh
          ansible.builtin.shell:
            cmd: "curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash"

        - name: Changing Default Shell to ZSH
          become: true
          user:
            name: "{{ ansible_user_id }}"
            shell: /bin/zsh

        - name: Changing Default ZSH Theme to spaceship
          ansible.builtin.lineinfile:
            path: /home/{{ ansible_user_id }}/.zshrc
            regexp: "^ZSH_THEME="
            line: 'ZSH_THEME="spaceship"'

        - name: Installing Spaceship
          ansible.builtin.shell:
            cmd: "git clone https://github.com/denysdovhan/spaceship-prompt.git ~/.oh-my-zsh/themes/spaceship-prompt"

        - name: Installing Oh-My-zsh
          ansible.builtin.shell:
            cmd: "ln -s /home/{{ ansible_user_id }}/.oh-my-zsh/themes/spaceship-prompt/spaceship.zsh-theme /home/{{ ansible_user_id }}/.oh-my-zsh/themes/spaceship.zsh-theme"

        - name: Creating ZSH Completion folder
          ansible.builtin.file:
            path: /home/{{ ansible_user_id }}/.oh-my-zsh/completions
            state: directory
            mode: 0755
        - name: Installing zsh-completions
          ansible.builtin.shell:
            cmd: "git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions"

        - name: Installing zsh-syntax-highlighting
          ansible.builtin.shell:
            cmd: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

        - name: Installing zsh-autosuggestions
          ansible.builtin.shell:
            cmd: "git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

        - name: Installing zsh-history-substring-search
          ansible.builtin.shell:
            cmd: "git clone https://github.com/zsh-users/zsh-history-substring-search ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search"

        - name: Installing fzf
          ansible.builtin.shell:
            cmd: "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install"

        - name: Changing Default ZSH
          ansible.builtin.blockinfile:
            block: "{{ lookup('file', 'files/zsh.add') }}"
            path: /home/{{ ansible_user_id }}/.zshrc
    - name: Install Terminator
      block:
        - name: Installing vim dracula
          ansible.builtin.shell:
            cmd: "git clone https://github.com/dracula/vim.git  ~/.vim/pack/themes/start/dracula"

        - name: Installing gnome-terminal Dracula
          ansible.builtin.shell:
            cmd: "git clone https://github.com/dracula/gnome-terminal ~/.oh-my-zsh/gnome-terminal"

        - name: Creatin Terminator folder
          ansible.builtin.file:
            path: /home/{{ ansible_user_id }}/.config/terminator
            state: directory
            mode: 0755

        - name: Copy Terminator config
          ansible.builtin.copy:
            src: files/config
            dest: ~/.config/terminator/config

        - name: Copy Vim
          ansible.builtin.copy:
            src: files/.vimrc
            dest: ~/.vimrc
    - name: Install collection Netbox
      block:
        - name: Force-install collection netbox.netbox
          community.general.ansible_galaxy_install:
            type: collection
            name: netbox.netbox
            force: true

        - name: Force-install collection community.general
          community.general.ansible_galaxy_install:
            type: collection
            name: community.general
            force: true
            
    - name: Install globalprotect-openconnect
      block:
        - name: Adicionar PPA yuezk/globalprotect-openconnect
          become: true
          ansible.builtin.shell:
            cmd: add-apt-repository --yes --update  ppa:yuezk/globalprotect-openconnect
        - name: Atualizar cache do apt
          become: true
          apt:
            update_cache: yes
        - name: Instalar pacote globalprotect-openconnect
          become: true
          apt:
            name: globalprotect-openconnect
            state: present
    - name: Install Apps
      block:
        - name: Instalar code com snap
          become: true
          ansible.builtin.shell:
            cmd: snap install --classic code

        - name: Instalar spotify com snap
          become: true
          ansible.builtin.shell:
            cmd: snap install spotify

        - name: Remover firefox com snap
          become: true
          ansible.builtin.shell:
            cmd: snap remove firefox
    - name: Install Chrome
      block:
        - name: Fazer download do pacote .deb do Chrome
          get_url:
            url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dest: /tmp/google-chrome-stable_current_amd64.deb

        - name: Instalar o pacote .deb do Chrome
          become: true
          apt:
            deb: /tmp/google-chrome-stable_current_amd64.deb
            state: present
    - name: Install extensions and reboot
      block:
        - name: install https://github.com/corecoding/Vitals
          git:
            dest: /home/{{ ansible_user_id }}/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com
            repo: https://github.com/corecoding/Vitals
            update: yes
            force: yes

        - name: install https://github.com/neffo/bing-wallpaper-gnome-extension
          git:
            dest: /home/{{ ansible_user_id }}/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com
            repo: https://github.com/neffo/bing-wallpaper-gnome-extension
            update: yes
            force: yes

        - name: install https://github.com/pop-os/shell.git
          git:
            dest: /tmp/shell
            repo: https://github.com/pop-os/shell.git
            update: yes
            force: yes

        - name: Installing shell
          ansible.builtin.shell:
            chdir: /tmp/shell
            cmd: make local-install

        - name: Unconditionally reboot the machine with all defaults
          ansible.builtin.reboot:
